fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
 
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/relybv/beng-profile_base.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    puppet: "https://github.com/abstractitptyltd/abstractit-puppet.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    role_bootstrap: "#{source_dir}"
